### ISSUE TITLE
Optional attributes and unknown children count

### ISSUE THREAD

**Issue by vovanz** [martinblech/xmltodict#111]
# What's wrong?
## 1. Optional attributes
If i have a tag which can look like this:
```xml
<sometag>blablabla</sometag>
```
or like this:
```xml
<sometag attr="123">blablabla</sometag>
```
In the first case parse result will look like this:
```python
{
    'sometag': 'blablabla'
}
```
and in the second case it will look like:
```python
{
    'sometag': {
        '@attr': '123',
         '#text': 'blablabla'
    }
}
```
So if I want to get its text content I can't just do something like:
```python
something = parse_result['sometag']['#text']
```
I have to write such ugly things:
```python
something = parse_result['sometag']
something = something['#text'] if type(something) is OrderedDict else something
```

## 2. Unknown children count
If I have a tag which can look like this:
```xml
<parent>
    <child>some text</child>
    <child>other text</child>
<parent>
```
And I don't know exact children count **(child could be only one!)**
So I couldn't iterate over children like this:
```python
for child in parse_result['parent']['child']:
    # some code
```
because list would be used only if there are more than one child.
So in this case I also have to perform some ugly type checking.
Like this:
```python
children = parse_result['parent']['child']
children = children if type(children) is list else [children]
for child in children:
    # some code
```
# Suggestion
I suggest to add special mode (triggered by special optional argument passed to *parse* function).
In this mode it will always use dictionary for describing tags and always use lists for describing children tags.

**Comment by ngoonee** [comment]
I was just planning to raise this issue after hitting it in a new project I'm doing. My initial reaction to 2. was 'yes, exactly'.

I've thought about it a bit more though, and realize that in nested situations this would be a real mess. So for example this:-
```xml
<parent>
    <sub>
        <child>some text</child>
        <child>other text</child>
    </sub>
</parent>
```
would require this:-
```python
children = parse_result['parent'][0]['sub'][0]['child']
```

That being said, an optional argument to parse as suggested would be welcome as a convenience. Better yet if it only applies to leaves and not intermediates.

**Comment by candlerb** [comment]
*(Moving this suggestion from closed ticket #14)*

What you could do is to nominate particular elements which should always generate lists, e.g.

~~~
xmltodict.parse(xml, force_list=set('child'))
~~~

This is the approach taken by Perl's XML::Simple with the [ForceArray](http://search.cpan.org/~grantm/XML-Simple-2.20/lib/XML/Simple.pm#ForceArray_=>_[_names_]_#_in_-_important) setting.

A problem with this is that if the `<sub>` element is empty, it's not going to give you an empty list of `{"child": []}`. This is due to how xmltodict groups elements at a lower level, i.e. it's not `sub` which is a list of child elements, but `child` which is a list.

So to work with xmltodict, I think you need to specify the enclosing element as well:

~~~
xmltodict.parse(xml, force_list={'sub': 'child'})
~~~

Implies: "if you see a `<sub>` element then always build a `<child>` with empty list underneath it".  Any actual `<child>` elements will then be added to that list, and will be consistent for 0, 1 or more elements.

Aside: there is a related but different problem, which is dealing with a heterogenous sequence of repeating elements. For example:

~~~
<stuff>
  <foo>.1.</foo>
  <bar>.2.</bar>
  <bar>.3.</bar>
  <foo>.4.</foo>
  <bar>.5.</bar>
</stuff>
~~~

At the moment you get:

~~~
OrderedDict([(u'stuff', OrderedDict([(u'foo', [u'.1.', u'.4.']), (u'bar', [u'.2.', u'.3.', u'.5.'])]))])
~~~

which loses the ordering relationship between the `foo` and `bar` elements.

This would have to be dealt with differently. For example:

~~~
xmltodict.parse(xml, force_list={'stuff': True})
~~~

could mean that `<stuff>` is forced to have a list of children, and that this list should contain repeated elements rather than grouped elements.  I don't know how practical that is to implement though.  And it would probably have implications for unparse.

**Comment by ngoonee** [comment]
I suspect as with most open-source projects that unless we can show some code, this won't move anywhere.

**Comment by candlerb** [comment]
Usually we look for some steer from project owner. Otherwise there is a risk of implementing something only to be told "no I don't like that solution, do XYZ instead"

**Comment by ngoonee** [comment]
There's been no response in months, though. I personally have just worked around it in my own code, uglily.

**Comment by martinblech** [comment]
Have you looked at pull request #120? If it doesn't cover this use case, I'll be happy to review and merge any pull request as long as:

a) It doesn't complicate the simplest use cases.
b) It has tests and documentation.

**Comment by ngoonee** [comment]
It covers it for me, though not hard to imagine situations where this would be a pain (as in my 22 Sep comment). However since this would not be default behaviour, callers would be expected to deal with that gracefully.

I like candlerb's suggestion but that would both be more work and probably more brittle as well (hence harder to properly test).

**Comment by martinblech** [comment]
The guiding principle behind the design of xmltodict is to implement **one simple mapping** between XML and nested dict+list+string structures resembling what you would get from a JSON document, no more, no less. I have no intention of making xmltodict a full fledged XML processing framework and I think that features like the one proposed in this ticket come at the expense of the library's ease of use and code simplicity/maintainability.

IMHO, if you're hitting xmltodict's limitations, you should use XPath over the excellent [lxml](http://lxml.de/).

Of course I could be wrong, if so please prove it with a pull request that I'll be glad to review and merge as long as the library remains easy to use, simple and maintainable.

**Comment by SeanHayes** [comment]
I'd be happy with the `children = parse_result['parent'][0]['sub'][0]['child']` behavior in all cases, it minimizes the number of code paths I need in my own applications. Otherwise I need an if condition for every node level.

Otherwise I'm loving this library, thanks!

**Comment by martinblech** [comment]
@SeanHayes You can already achieve this effect using this snippet:
```python
from collections import defaultdict
xmltodict.parse(xml, dict_constructor=lambda *args, **kwargs: defaultdict(list, *args, **kwargs))
```
