### ISSUE TITLE
Is there a way to keep order of mixed and repeating tags?

### ISSUE THREAD

**Issue by andreif** [martinblech/xmltodict#125]
Example :hamburger: 

```xml
<DoubleCheeseburger>
    <Bread/>
    <Cheese/>
    <Beef/>
    <Cheese/>
    <Beef/>
    <Bread/>
</DoubleCheeseburger>
```

```py
import xmltodict, json
data = xmltodict.parse(double_cheeseburger_xml)
print(json.dumps(data, indent=3))
```

```json
{
   "DoubleCheeseburger": {
      "Bread": [
         null,
         null
      ],
      "Cheese": [
         null,
         null
      ],
      "Beef": [
         null,
         null
      ]
   }
}
```
Can we tell the order of each `Bread`, `Cheese` and `Beef` with respect to each other not only within the same tag, but also in the parent node (`DoubleCheeseburger`)?

If not, is there a way to monkeypatch to write it down?

**Comment by andreif** [comment]
Well, it's seems that case is outside of `xmltodict`'s scope and I could simply make my own handler and create a data structure solving the problem in my case (WSDL). I doubt there is any benefit for `xmltodict` to handle it.

**Comment by berteh** [comment]
AFAIK the order of children has no meaning in "pure" XML. A semantically valid option may be, if that's acceptable to you, to add an attribute "@position" or "@order" to the elements you want to have in some sequence.

This information would then be available for querying/sorting/filtering/whatever, and since the elements would have difference sequence attributes they would not be considered as duplicates by the parser (and thus not "merged").

**Comment by andreif** [comment]
Some services do require certain order of children unfortunately.

**Comment by lindsay-stevens** [comment]
@andreif: I needed the same feature and wrote a patch for that, the branch is on my fork here: https://github.com/lindsay-stevens/xmltodict/tree/ordered-children-short-tags

It's got a flag to deal with mixed child ordering on parse and unparse. During parse it'll add an @\__order\__ attribute, on unparse it'll remove the attribute and sort the mixed nodes. Also has a bonus XHTML-ish feature to enable output of short-form of empty tags, e.g. "\<tag/\>" vs. "\<tag\>\</tag\>"

Not opened a PR for it yet since my previous one is still open and I didn't want to be annoying.

**Comment by iandanforth** [comment]
@lindsay-stevens This was very helpful. I hope you do open that as a PR as it would be nice to be able to move back to mainline.

**Comment by fedorov** [comment]
I had the same need, and I tried @lindsay-stevens branch - this helps a lot, thank you! 👍 

+1 for a PR!

**Comment by eemjema** [comment]
Thank you @lindsay-stevens!
