### ISSUE TITLE
xml containing 1 child

### ISSUE THREAD

**Issue by ocZio** [martinblech/xmltodict#14]
Consider the following code

``` python
xml = """<?xml version="1.0" encoding="utf-8" ?>
<root>
    <children>
        <child>
            <name>A</name>
        </child>
    </children>
</root>"""

xmltodict.parse(xml)['root']['children']['child']
```

Wouldn't you expect to have an iterable object even when there is only 1 child?

**Comment by foxx** [comment]
Given that this issues keeps coming up for many people, myself included, would you entertaining making this the default dict constructor in the next major release? It is surprising behaviour to say the least.

**Comment by martinblech** [comment]
@foxx I understand it can be annoying, but I think the other option is even worse. For example, with this XML:
```xml
<config>
  <settings>
    <value1>0</value1>
    <value2>false</value2>
  </settings>
  <logging>
    <value3>1</value3>
    <value4>true</value4>
  </logging>
</config>
```

I would expect a `dict` like this:
```python
{
    "config": {
        "settings": {
            "value1": "0",
            "value2": "false"
        },
        "logging": {
            "value3": "1",
            "value4": "true"
        },
    }
}
```

But with your proposal I would get this instead:
```python
{
    "config": [{
        "settings": [{
            "value1": ["0"],
            "value2": ["false"]
        }],
        "logging": [{
            "value3": ["1"],
            "value4": ["true"]
        }],
    }]
}
```

In order to access the configuration values, you would have to use `d['config'][0]['settings'][0]['value1'][0]` instead of `d['config']['settings']['value1']`. Other users might think this is surprising behavior too, so I believe which option is better depends on the use case.

Also, the Python standard library doesn't have a `DefaultDict` that is also an `OrderedDict`. If I followed your suggestion and used `DefaultDict` in the next release, `xmltodict` would lose the elements' ordering information, which could also be surprising for some use cases (and break code that depends on this).

**Comment by kmonsoor** [comment]
as an user, i also agree with @martinblech . otherwise, the output will get too confusing

**Comment by martinblech** [comment]
The best we can do about this is improve the documentation, I think. @foxx, what would you add to the README to make this behavior less surprising?

**Comment by foxx** [comment]
@martinblech I would be inclined to agree with you, I just tried the previously mentioned workaround and was met with the annoyance of having to reference everything with [0].

It's difficult to say which would be better, because like you said it depends on use case. For my own use case I have ended up using `pyQuery` which is a bit better for us.

I'm almost tempted to say that adding something to the README would be unlikely to make a difference, as most people will not read the entire thing.

**Comment by KenetJervet** [comment]
It might be annoying to reference everything with [0] but for certain cases it provide a unified approach to access arbitrary xml documents.

As a side question:
For such document:
```
<a>
    <b></b>
</a>
```
I get an object like this: {"a": [ { "b": [None] } ]}
I understand that a None is placed to represent an empty b node, but Is it possible to get a {} instead?
It's easier to modify the object since I can assume there's always a valid dict to manipulate.

**Comment by candlerb** [comment]
What you could do is to nominate particular elements which should always generate lists, e.g.

~~~
xmltodict.parse(xml, force_list=set('child'))
~~~

This is the approach taken by Perl's XML::Simple with the [ForceArray](http://search.cpan.org/~grantm/XML-Simple-2.20/lib/XML/Simple.pm#ForceArray_=>_[_names_]_#_in_-_important) setting.

A problem with this is that if the `<children>` element is empty, it's not going to give you an empty list of `{"child": []}`. This is due to how xmltodict groups elements at a lower level, i.e. it's not `children` which is a list, but `child` which is a list.

So to work with xmltodict, I think you need to specify the enclosing element as well:

~~~
xmltodict.parse(xml, force_list={'children': 'child'})
~~~

Implies: "if you see a `<children>` element then always build a `<child>` with empty list underneath it".  Any actual `<child>` elements will then be added to that list.

Aside: there is a related but different problem, which is dealing with a heterogenous sequence of repeating elements. For example:

~~~
<stuff>
  <foo>.1.</foo>
  <bar>.2.</bar>
  <bar>.3.</bar>
  <foo>.4.</foo>
  <bar>.5.</bar>
</stuff>
~~~

At the moment you get:

~~~
OrderedDict([(u'stuff', OrderedDict([(u'foo', [u'.1.', u'.4.']), (u'bar', [u'.2.', u'.3.', u'.5.'])]))])
~~~

which loses the ordering relationship between the `foo` and `bar` elements.

This would have to be dealt with differently. For example:

~~~
xmltodict.parse(xml, force_list={'stuff': True})
~~~

could mean that `<stuff>` is forced to have a list of children, and that this list should contain repeated elements rather than grouped elements.  I don't know how practical that is to implement though.  And it would probably have implications for unparse.

**Comment by kadnan** [comment]
@candlerb 
```
TypeError: __init__() got an unexpected keyword argument 'force_list'
```

**Comment by candlerb** [comment]
Correct. It hasn't been implemented yet :-)

**Comment by kadnan** [comment]
@candlerb I found the implementation in `master` not in `pip` version:
```
sudo pip install git+https://github.com/martinblech/xmltodict.git@master
```

**Comment by martinblech** [comment]
@kadnan @candlerb this feature is already out in the 0.10.1 release. Which version are you running on? I just did a fresh install and it worked fine:

```sh
$ pip install xmltodict
Collecting xmltodict
  Downloading xmltodict-0.10.1.tar.gz
Building wheels for collected packages: xmltodict
  Running setup.py bdist_wheel for xmltodict ... done
  Stored in directory: /Users/martinblech/Library/Caches/pip/wheels/06/23/c0/b5e91910dc6261d118f437bc4c487972e3b00147e09372f8bc
Successfully built xmltodict
Installing collected packages: xmltodict
Successfully installed xmltodict-0.10.1
$ python
Python 2.7.11 (default, Feb 22 2016, 19:49:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmltodict
>>> xml = '''
... <stuff>
...   <foo>.1.</foo>
...   <bar>.2.</bar>
...   <bar>.3.</bar>
...   <foo>.4.</foo>
...   <bar>.5.</bar>
... </stuff>
... '''
>>> xmltodict.parse(xml, force_list={'stuff': True})
OrderedDict([(u'stuff', [OrderedDict([(u'foo', [u'.1.', u'.4.']), (u'bar', [u'.2.', u'.3.', u'.5.'])])])])
>>>
```

**Comment by kadnan** [comment]
@martinblech When I installed from default pip repo it did not pull the right version

**Comment by kadnan** [comment]
Ok, What I figured out that I Had an older version installed a year back and I found the above link from Github and installed like that. Just uninstalled and installed again by doing `sudo pip install xmltodict` and it installed the latest version.

Sorry for confusion.

**Comment by martinblech** [comment]
No problem, glad it worked in the end.

**Comment by acjackson** [comment]
How can I use the `force_list` option for ALL elements?
Do I really have to list every element?

**Comment by candlerb** [comment]
Try changing this:

```
    def _should_force_list(self, key, value):
        if not self.force_list:
            return False
        try:
            return key in self.force_list
        except TypeError:
            return self.force_list(self.path[:-1], key, value)
```

to:

```
    def _should_force_list(self, key, value):
        if not self.force_list:
            return False
        if isinstance(self.force_list, bool):
            return self.force_list
        try:
            return key in self.force_list
        except TypeError:
            return self.force_list(self.path[:-1], key, value)
```

If that works, please submit a PR.

**Comment by jknaus** [comment]
Thank you. This worked for me. I submitted a PR.

**Comment by michaelgeiser** [comment]
So, just to check my understanding if I have this (abbreviated) XML, Martin's position is that the ASSET nodes with only one EVENT should be rendered differently than the nodes with two or more EVENT nodes??!! I do not see how that makes any sense; if there are non-zero nodes, "1 to n" child nodes should be handled the same way without having to parse anything differently or handle a single node as a special case in my code...that seems very unpythonic and does not seem like a "feature".  I get the argument, but for XML processing in python, I do not think it is a valid argument when you need a general case that fits how XML is created and used.

<root>
	<JBUS_EVENTS>
		<ASSET id="3">
			<EVENT>
				<TIMESTAMP>1543940634</TIMESTAMP>
			</EVENT>
		</ASSET>
		<ASSET id="9">
			<EVENT>
				<TIMESTAMP>1544017455</TIMESTAMP>
			</EVENT>
		</ASSET>
		<ASSET id="17">
			<EVENT>
				<TIMESTAMP>1543981524</TIMESTAMP>
			</EVENT>
			<EVENT>
				<TIMESTAMP>1543981528</TIMESTAMP>
			</EVENT>
		</ASSET>
		<ASSET id="21">
			<EVENT>
				<TIMESTAMP>1543992969</TIMESTAMP>
			</EVENT>
			<EVENT>
				<TIMESTAMP>1543985289</TIMESTAMP>
			</EVENT>
			<EVENT>
				<TIMESTAMP>1543996749</TIMESTAMP>
			</EVENT>
			<EVENT>
				<TIMESTAMP>1544008151</TIMESTAMP>
			</EVENT>
		</ASSET>
		<ASSET id="23">
			<EVENT>
				<TIMESTAMP>1544015746</TIMESTAMP>
			</EVENT>
			<EVENT>
				<TIMESTAMP>1543941430</TIMESTAMP>
			</EVENT>
		</ASSET>
	</JBUS_EVENTS>
</root>

**Comment by michaelgeiser** [comment]
The real issue shows that each EVENT node has several children.  If I consistently get an iterator, I can code this

`for jbus_event in zonar_telemetry_data['zonar']['JBUS_EVENTS']['ASSET']:

    for jbus_event_children in jbus_event['EVENT']:
        readable = None

        try:
            # readable = datetime.datetime.fromtimestamp(int(jbus_event1['TIMESTAMP'])).isoformat()
            readable = jbus_event_children['TIMESTAMP']
        except Exception:
            print(str(jbus_event_children['TIMESTAMP']))
            # TODO handle this correctly!!!

        jbus_events_output.append({
            'VIN': jbus_event['@vin'],
            'gps': asset_gps_dict[jbus_event['@id']],
            'TIMESTAMP': jbus_event_children['TIMESTAMP'],
            'Readable Timestamp': readable,
            'PROTOCOL': jbus_event_children['PROTOCOL'],
            'SA': jbus_event_children['SA'],
            'FMI': jbus_event_children['FMI'],
            'SPN': jbus_event_children['SPN'],
            'MID': jbus_event_children['MID'],
            'PIDISD': jbus_event_children['PIDSID'],
            'ISPID': jbus_event_children['ISPID'],
            'DESC': jbus_event_children['DESC'],
            'ODOMETER': jbus_event_children['ODOMETER'],
            'ENGINE HRS': jbus_event_children['ENGINEHOURS'],
            'COOLENT TEMP': jbus_event_children['COOLANTTEMP'],
            'OIL PRESSURE': jbus_event_children['OILPRESSURE'],
            'LATITUDE': jbus_event_children['LAT'],
            'LONGITUDE': jbus_event_children['LON'],
            'OC': jbus_event_children['OC'],
            'MIL': jbus_event_children['MIL'],
            'CHKENG': jbus_event_children['CHKENG'],
            'STPENG': jbus_event_children['STPENG']
        })

        pp.pprint(jbus_events_output)`

**Comment by martinblech** [comment]
@michaelgeiser please read the conversation above and @jknaus's PR. Your use case is exactly what force_list is for.

**Comment by michaelgeiser** [comment]
Martin, I did read the conversation and understood it.  The point, in other terms, is that force_list should be the default behavior.  Because of the nature and intent of xml, for any child node, it is much more likely that at SOME point in your XML document, you'll have a structure that can have 1 or more child nodes.  Without uniformly handling "1 child node" and "more than 1 child nodes" use cases, you have to write ugly code that has different implementations for "1" or "more than 1" child node use cases whereas a single case would be fine to handle both.  The problem is further extended if, link in the EVENT structure I used, you need to examine the data.  If the EVENT node has a varying number of child nodes, it is difficult to determine if you've iterated over all the EVENT child nodes without an iterator, especially since python doesn't have a convenient hasNext() function; you (almost) have to know the number of nodes and node names or so some silly unpythonic coding that should not pass a code review to get the data.

If I do not use force_list, I have to test the type of jbus_event_children and have two implementations if it's a str or an collections.OrderedDict. 

So if I have to use force_list on all xml files to parse, since you generally do not know that **_every_** child node will have the same structure, it seems like making the default behavior is logical.

**Comment by candlerb** [comment]
> So if I have to use force_list on all xml files to parse, since you generally do not know that **_every_** child node will have the same structure, it seems like making the default behavior is logical.

xmltodict is not meant to be a processor for generic XML documents not in an expected structure; use an XML parser which gives you a DOM model for that.

Rather, it's for convenient reading of XML containing structured data.  If all children were forced to be lists, it would be annoying as hell for those elements which are never lists:

* `info[0].name[0]`
* `info[0].code[0]`
* `info[0].quantity[0]`
... etc

But see #204 and use `force_list=True` if you really want this.

**Comment by michaelgeiser** [comment]
Why do you say that "xmltodict is not meant to be a processor for generic XML documents not in an expected structure"  based on the first line of the repo, "Python module that makes working with XML feel like you are working with JSON" kinda implies it is for generic XML documents.

The is not sending unexpected repeated elements, that is the contract and in some cases there are 1 child nodes, in other cases, more than 1 child node...

**Comment by candlerb** [comment]
xmltodict doesn't implement all XML features.  It doesn't handle mixed content, for example.  It offers a simplified view of XML, to avoid you having to deal with the DOM directly. 

If you expect that a particular node could have 1 or more instances of node type "foo", then you should use `force_list=['foo']`

For an example of why it would be bad to make all child elements be lists, please see [this comment](https://github.com/martinblech/xmltodict/issues/14#issuecomment-69913281).

**Comment by michaelgeiser** [comment]
That comment was not in line with what anyone was proposing

This is the right example:

<config>
  <settings>
    <value1>0</value1>
    <value2>false</value2>
  </settings>
  <settings>
    <value1>1</value1>
  </settings>
  <settings>
    <value1>2</value1>
    <value2>true</value2>
  </settings>  
  <logging>
    <value3>1</value3>
    <value4>true</value4>
  </logging>
</config>

currently gives
{
    "config": {
        "settings": {[
            "value1": "0",
            "value2": "false"],
	    "value1": "1",
	    [ "value1": "2",
            "value2": "true"]
        },
        "logging": {
            "value3": "1",
            "value4": "true"
        },
    }
}

I'd expect this
{
    "config": {
        "settings": {
            ["value1": "0",
            "value2": "false"],
			["value1": "1"],
			["value1": "2",
            "value2": "true"]
        },
        "logging": {
            "value3": "1",
            "value4": "true"
        },
    }
}

no one has or would suggest putting the **_values_** in lists; that would be stupid

**Comment by franck-noahk** [comment]
Could you give full example showing how to use force_list=[string] I can't seem to get it to work.

**Comment by candlerb** [comment]
Show what you tried.

**Comment by pdunk** [comment]
I tried using it as well with multiple elements and it complains.
I am using Python2 and got: xmltodict==0.12.0

I tried:
force_list={'cast_crew':True}
xmltodict.parse(ElementTree.tostring(xmlnode, method='xml'),force_list)

I get this error:
TypeError: ParserCreate() argument 1 must be string or None, not dict

**Comment by chiarcos** [comment]
`force_list()` works nicely, but this needs to be more prominently documented. It took me quite a while to find that here.
