### ISSUE TITLE
Child Order Not Maintained with Different Tags

### ISSUE THREAD

**Issue by mcrowson** [martinblech/xmltodict#182]
If there is a generic doc that has 4 elements, but one in the middle has a different tag name, that order is not persisted in the round trip

```python
>>> xml = """<doc><el>1</el><el>2</el><el1>3</el1><el>4</el></doc>"""
>>> d = xmltodict.parse(xml)
>>> round_trip = xmltodict.unparse(d)
>>> print(round_trip)
'<doc><el>1</el><el>2</el><el>4</el><el1>3</el1></doc>'
```

As you can see the el1 got moved to the end.

**Comment by martinblech** [comment]
Hi! Unfortunately this a limitation of the way xml gets translated to nested dict+list structures, it's not possible to preserve the ordering in this case without introducing extra information to the data structure.

**Comment by mcrowson** [comment]
And there is no desire to retain that information in the data structure?

**Comment by martinblech** [comment]
It's a tradeoff: in order to retain that information one would have to introduce extra information into the dict+list structure, where instead of a string there would have to be a more complex object that contains both the string and the relative ordering of the element within the container. This would complicate the typical, simple use case that this library is good for, in order to solve for an edge case.

What's exactly the use case here?

**Comment by stacywsmith** [comment]
@mcrowson You might consider https://github.com/Juniper/jxmlease/ which does maintain ordering.

**Comment by martinblech** [comment]
@stacywsmith that library looks great! Thanks for sharing.

**Comment by nlevitt** [comment]
@stacywsmith jxmlease seems to have the same problem?!??
```
>>> s = '''
... <foo>
...   <a>one</a>
...   <b>two</b>
...   <a>three</a>
... </foo>
... '''
>>> print(jxmlease.parse(s).emit_xml())
<?xml version="1.0" encoding="utf-8"?>
<foo>
    <a>one</a>
    <a>three</a>
    <b>two</b>
</foo>
```

**Comment by fedorov** [comment]
I think the solution discussed in this comment addresses the original issue raised here: https://github.com/martinblech/xmltodict/issues/125#issuecomment-247917699
